import 'package:flutter/material.dart';
import 'package:speech_translator/models/fln_models.dart';

class FlnCurriculumData {
  // -------------------------------------------------------------
  // 1. NIPUN BHARAT COMPETENCIES
  // -------------------------------------------------------------
  static const List<NipunCompetency> competencies = [
    NipunCompetency(
      code: "FL-BV-01",
      subject: FlnSubject.literacy,
      grade: FlnGrade.balvatika,
      titleHindi: "मौखिक भाषा विकास एवं चित्र पठन",
      titleSantali: "ᱢᱚᱪᱟ ᱨᱚᱲ ᱦᱟᱨᱟ ᱟᱨ ᱪᱤᱛᱟᱹᱨ ᱯᱟᱲᱦᱟᱣ",
      learningOutcome: "बच्चे चित्रों को देखकर अपनी मातृभाषा में सरल वाक्य बोलते हैं और बातचीत में भाग लेते हैं।",
    ),
    NipunCompetency(
      code: "FL-G1-01",
      subject: FlnSubject.literacy,
      grade: FlnGrade.grade1,
      titleHindi: "ध्वनि-प्रतीक सम्बंध (ओल चिकी वर्णमाला)",
      titleSantali: "ᱥᱟᱰᱮ-ᱪᱤᱱᱦᱟᱹ ᱡᱚᱲᱟᱣ (ᱚᱞ ᱪᱤᱠᱤ ᱟᱠᱷᱚᱨ)",
      learningOutcome: "बच्चे ओल चिकी के 5 मूल अक्षरों (ᱚ, ᱛ, ᱜ, ᱝ, ᱞ) की ध्वनि पहचानते हैं और उनसे शुरू होने वाले शब्द बोलते हैं।",
    ),
    NipunCompetency(
      code: "FL-G2-01",
      subject: FlnSubject.literacy,
      grade: FlnGrade.grade2,
      titleHindi: "सरल शब्द पठन एवं लेखन",
      titleSantali: "ᱟᱞᱜᱟ ᱥᱟᱵᱟᱫᱽ ᱯᱟᱲᱦᱟᱣ ᱟᱨ ᱚᱞ",
      learningOutcome: "बच्चे 2-3 अक्षरों वाले संथाली शब्दों को प्रवाहपूर्ण ढंग से पढ़ते हैं और अर्थ समझते हैं।",
    ),
    NipunCompetency(
      code: "FL-G3-01",
      subject: FlnSubject.literacy,
      grade: FlnGrade.grade3,
      titleHindi: "लघु कथा एवं समझ के साथ पठन",
      titleSantali: "ᱠᱷᱟᱴᱚ ᱠᱟᱹᱦᱱᱤ ᱟᱨ ᱵᱩᱡᱷᱟᱹᱣ ᱥᱟᱶ ᱯᱟᱲᱦᱟᱣ",
      learningOutcome: "बच्चे 40-50 शब्दों की स्थानीय लोककथा पढ़ते हैं और पूछे गए प्रश्नों के सटीक उत्तर देते हैं।",
    ),
    NipunCompetency(
      code: "FN-BV-01",
      subject: FlnSubject.numeracy,
      grade: FlnGrade.balvatika,
      titleHindi: "पूर्व-संख्या अवधारणा (बड़ा-छोटा, कम-ज्यादा)",
      titleSantali: "ᱞᱮᱠᱷᱟ ᱢᱟᱬᱟᱝ ᱫᱷᱟᱨᱚᱬᱟ (ᱢᱟᱨᱟᱝ-ᱦᱩᱰᱤᱧ, ᱠᱚᱢ-ᱰᱷᱮᱨ)",
      learningOutcome: "बच्चे वस्तुओं को उनके आकार और मात्रा के आधार पर वर्गीकृत करते हैं।",
    ),
    NipunCompetency(
      code: "FN-G1-01",
      subject: FlnSubject.numeracy,
      grade: FlnGrade.grade1,
      titleHindi: "1 से 10 तक संख्याओं की गिनती एवं पहचान",
      titleSantali: "᱑ ᱠᱷᱚᱱ ᱑᱐ ᱫᱷᱟᱹᱵᱤᱡ ᱞᱮᱠᱷᱟ ᱟᱨ ᱪᱤᱱᱦᱟᱹᱣ",
      learningOutcome: "बच्चे 1 से 10 तक की वस्तुओं को संथाली (ᱢᱤᱫ, ᱵᱟᱨ, ᱯᱮ...) में गिनते हैं और ओल चिकी अंकों को पहचानते हैं।",
    ),
    NipunCompetency(
      code: "FN-G2-01",
      subject: FlnSubject.numeracy,
      grade: FlnGrade.grade2,
      titleHindi: "20 तक वस्तुओं का जोड़ (मिलाना)",
      titleSantali: "᱒᱐ ᱫᱷᱟᱹᱵᱤᱡ ᱡᱤᱱᱤᱥ ᱢᱮᱥᱟ (ᱡᱚᱲᱟᱣ)",
      learningOutcome: "बच्चे कंकड़/तीली की सहायता से 10-20 तक की संख्याओं का जोड़ करते हैं।",
    ),
    NipunCompetency(
      code: "FN-G3-01",
      subject: FlnSubject.numeracy,
      grade: FlnGrade.grade3,
      titleHindi: "दैनिक जीवन में संथाली स्थानीय माप एवं घटाव",
      titleSantali: "ᱫᱤᱱᱟᱹᱢ ᱡᱤᱭᱚᱱ ᱨᱮ ᱡᱚᱠᱷᱟ ᱟᱨ ᱜᱷᱟᱴᱟᱣ",
      learningOutcome: "बच्चे संथाली पारंपरिक माप (ᱯᱟᱹᱭᱞᱟᱹ, ᱠᱟᱴᱷᱟ) और दैनिक लेन-देन में घटाव को समझते हैं।",
    ),
  ];

  // -------------------------------------------------------------
  // 2. STRUCTURED FLN LESSON SCRIPTS
  // -------------------------------------------------------------
  static const List<LessonScript> lessonScripts = [
    LessonScript(
      id: "LS-LIT-01",
      titleHindi: "पाठ 1: हमारे पशु-पक्षी (चित्र देखकर बातचीत)",
      titleSantali: "ᱯᱟᱴᱷ ᱑: ᱟᱵᱚᱨᱤᱱ ᱡᱤᱵᱽ-ᱡᱤᱭᱟᱹᱞᱤ (ᱪᱤᱛᱟᱹᱨ ᱧᱮᱞᱛᱮ ᱨᱚᱯᱚᱲ)",
      competencyCode: "FL-BV-01",
      grade: FlnGrade.balvatika,
      subject: FlnSubject.literacy,
      totalDurationMinutes: 35,
      learningOutcome: "बच्चे घरेलू जानवरों के संथाली नाम पहचानेंगे और अपनी भाषा में 1-1 वाक्य बोलेंगे।",
      materialsNeeded: [
        "जानवरों के चित्र कार्ड (गाय, बकरी, कुत्ता, मुर्गी)",
        "संथाली बालगीत चार्ट",
        "टैबलेट ऑडियो स्पीकर"
      ],
      phases: [
        LessonPhase(
          phaseNameHindi: "चरण 1: गोल घेरा समय (Circle Time)",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱑: ᱜᱚᱞ ᱜᱷᱮᱨᱟ ᱚᱠᱛᱚ",
          durationMinutes: 5,
          teacherDialogueHindi: "सभी बच्चे गोल घेरे में बैठ जाओ। आज हम जानवरों के बारे में बातचीत करेंगे।",
          santaliOlChiki: "ᱥᱟᱱᱟᱢ ᱜᱤᱫᱽᱨᱟᱹ ᱜᱚᱞ ᱜᱷᱮᱨᱟ ᱛᱮ ᱫᱩᱲᱩᱵᱽᱯᱮ᱾ ᱛᱮᱦᱮᱧ ᱫᱚ ᱡᱤᱵᱽ-ᱡᱤᱭᱟᱹᱞᱤ ᱵᱟᱵᱚᱛ ᱵᱚ ᱨᱚᱯᱚᱲᱟ᱾",
          santaliLatin: "Sanam gidra gol ghera te durobpe. Tehenj do jib-jiyali babat bo roporaa.",
          santaliDevanagari: "सानाम गिद्रा गोल घेरा ते दुरुबपे। तेहेंज दो जिब-जियाली बाबत बो रोपड़ा।",
          activityInstructionsHindi: "बच्चों के साथ हाथ पकड़कर संथाली स्वागत गीत गाएं।",
          studentAction: "बच्चे घेरा बनाकर बैठते हैं और शिक्षक का अभिवादन करते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 2: अवधारणा परिचय (चित्र प्रदर्शन)",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱒: ᱪᱤᱛᱟᱹᱨ ᱩᱫᱩᱜ ᱥᱟᱶ ᱩᱯᱨᱩᱢ",
          durationMinutes: 10,
          teacherDialogueHindi: "यह चित्र देखो! यह गाय है। संथाली में इसे 'गाई' कहते हैं। बोलो - गाई!",
          santaliOlChiki: "ᱱᱚᱣᱟ ᱪᱤᱛᱟᱹᱨ ᱧᱮᱞᱯᱮ! ᱱᱚᱣᱟ ᱫᱚ ᱜᱟᱹᱭ ᱠᱟᱱᱟᱭ᱾ ᱥᱟᱱᱛᱟᱲᱤ ᱛᱮ 'ᱜᱟᱹᱭ' ᱵᱚ ᱢᱮᱛᱟᱭᱟ᱾ ᱢᱮᱱᱯᱮ - ᱜᱟᱹᱭ!",
          santaliLatin: "Nowa chitar nyelpe! Nowa do gai kanay. Santali te 'gai' bo metaya. Menpe - gai!",
          santaliDevanagari: "नोवा चितार ञेलपे! नोवा दो गई कानाय। सांताड़ी ते 'गई' बो मेताया। मेनपे - गई!",
          activityInstructionsHindi: "गाय, बकरी (मेरोम), कुत्ता (सेता), और बिल्ली (पुसी) के चित्र दिखाकर संथाली नाम दोहराएं।",
          studentAction: "बच्चे चित्र देखकर संथाली में नाम दोहराते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 3: निर्देशित अभ्यास (पहचानो और बताओ)",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱓: ᱧᱮᱞ ᱪᱤᱱᱦᱟᱹᱣ ᱚᱵᱷᱟᱥ",
          durationMinutes: 10,
          teacherDialogueHindi: "अब बताओ, आपके घर में कौन सा जानवर है? बिल्ली को क्या कहते हैं?",
          santaliOlChiki: "ᱱᱤᱛᱚᱜ ᱞᱟᱹᱭᱯᱮ, ᱟᱯᱮ ᱚᱲᱟᱜ ᱨᱮ ᱚᱠᱚᱭ ᱡᱤᱣᱤ ᱢᱮᱱᱟᱭᱟ? ᱵᱤᱞᱟᱹᱭ ᱫᱚ ᱪᱮᱫ ᱵᱚ ᱢᱮᱛᱟᱭᱟ?",
          santaliLatin: "Nitog laype, ape orag re okoy jiwi menaya? Bilai do chet bo metaya?",
          santaliDevanagari: "नितोक लयपे, आपे ओड़ाक रे ओकोय जीवी मेनाया? बिलाई दो चेद बो मेताया?",
          activityInstructionsHindi: "शिक्षक चित्र छिपाते हैं और संथाली ध्वनि की नकल कर बच्चों से नाम पूछते हैं।",
          studentAction: "बच्चे 'पुसी' (बिल्ली) और 'सेता' (कुत्ता) कहकर उत्साह से बताते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 4: समूह गतिविधि (अभिनय खेल)",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱔: ᱫᱚᱞ ᱠᱟᱹᱢᱤ ᱟᱨ ᱮᱱᱮᱡ",
          durationMinutes: 7,
          teacherDialogueHindi: "एक बच्चा जानवर की आवाज़ निकालेगा, बाकी बच्चे संथाली में नाम बताएंगे!",
          santaliOlChiki: "ᱢᱤᱫ ᱜᱤᱫᱽᱨᱟᱹ ᱡᱤᱵᱽ ᱨᱮᱭᱟᱜ ᱥᱟᱰᱮ ᱚᱰᱚᱠᱟᱭ, ᱟᱨ ᱮᱴᱟᱜ ᱜᱤᱫᱽᱨᱟᱹ ᱥᱟᱱᱛᱟᱲᱤ ᱛᱮ ᱧᱩᱛᱩᱢ ᱯᱮ ᱞᱟᱹᱭᱟ!",
          santaliLatin: "Mit gidra jib reyag sade odokay, ar etag gidra Santali te nyutum pe laya!",
          santaliDevanagari: "मिद गिद्रा जिब रेयाक साडे ओडोकाय, आर एटाक गिद्रा सांताड़ी ते ञुतुम पे लया!",
          activityInstructionsHindi: "बच्चों के 2 समूह बनाएं और जानवर अभिनय प्रतियोगिता कराएं।",
          studentAction: "बच्चे संथाली शब्दों का प्रयोग करते हुए खेल में भाग लेते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 5: समापन एवं प्रशंसा",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱕: ᱢᱩᱪᱟᱹᱫ ᱟᱨ ᱥᱟᱨᱦᱟᱣ",
          durationMinutes: 3,
          teacherDialogueHindi: "शाबाश बच्चों! आज आप सभी ने बहुत अच्छा बोला। कल अपने घर के जानवरों के नाम लिखकर/चित्र बनाकर लाना।",
          santaliOlChiki: "ᱥᱟᱵᱟᱥ ᱜᱤᱫᱽᱨᱟᱹᱠᱚ! ᱛᱮᱦᱮᱧ ᱫᱚ ᱟᱹᱰᱤ ᱵᱮᱥ ᱯᱮ ᱨᱚᱲ ᱠᱮᱫᱟ᱾ ᱜᱟᱯᱟ ᱟᱯᱱᱟᱨ ᱚᱲᱟᱜ ᱨᱤᱱ ᱡᱤᱵᱽ ᱠᱚᱣᱟᱜ ᱪᱤᱛᱟᱹᱨ ᱟᱹᱜᱩᱭᱯᱮ᱾",
          santaliLatin: "Sabas gidrako! Tehenj do adi bes pe ror keda. Gapa apnar orag rin jib kowag chitar aguipe.",
          santaliDevanagari: "साबास गिद्राको! तेहेंज दो अडी बेस पे रोड़ केदा। गापा आपनार ओड़ाक रिन जिब कोवाक चितार अगुइपे।",
          activityInstructionsHindi: "सभी बच्चों के लिए ताली बजवाएं।",
          studentAction: "बच्चे ताली बजाते हैं और शिक्षक को 'जोहार' कहते हैं।",
        ),
      ],
    ),
    LessonScript(
      id: "LS-NUM-01",
      titleHindi: "पाठ 2: संथाली में गिनती (1 से 5 तक संख्या पहचान)",
      titleSantali: "ᱯᱟᱴᱷ ᱒: ᱥᱟᱱᱛᱟᱲᱤ ᱛᱮ ᱞᱮᱠᱷᱟ (᱑ ᱠᱷᱚᱱ ᱕ ᱫᱷᱟᱹᱵᱤᱡ)",
      competencyCode: "FN-G1-01",
      grade: FlnGrade.grade1,
      subject: FlnSubject.numeracy,
      totalDurationMinutes: 35,
      learningOutcome: "बच्चे 1 से 5 तक कंकड़ गिनेंगे और ओल चिकी अंक (᱑, ᱒, ᱓, ᱔, ᱕) पहचानेंगे।",
      materialsNeeded: [
        "रंगीन कंकड़ और तीलियां",
        "ओल चिकी संख्या कार्ड (1 से 5)",
        "गिनती फ्लैशकार्ड"
      ],
      phases: [
        LessonPhase(
          phaseNameHindi: "चरण 1: वार्म-अप (उंगलियों से गिनती)",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱑: ᱛᱤ ᱠᱟᱹᱴᱩᱵ ᱛᱮ ᱞᱮᱠᱷᱟ",
          durationMinutes: 5,
          teacherDialogueHindi: "अपनी उंगलियां ऊपर उठाओ! मेरे साथ गिनो: एक - मिद, दो - बार, तीन - पे, चार - पुन, पांच - मोड़े!",
          santaliOlChiki: "ᱟᱯᱮᱭᱟᱜ ᱛᱤ ᱠᱟᱹᱴᱩᱵ ᱪᱚᱴ ᱛᱩᱞᱯᱮ! ᱤᱧ ᱥᱟᱶ ᱞᱮᱠᱷᱟᱭᱯᱮ: ᱢᱤᱫ, ᱵᱟᱨ, ᱯᱮ, ᱯᱩᱱ, ᱢᱚᱬᱮ!",
          santaliLatin: "Apeyag ti katub chot tulpe! Inj saw lekhaype: Mit, Bar, Pe, Pun, More!",
          santaliDevanagari: "आपेयाक ती काटुब चोट तुलपे! इंज साव लेखायपे: मिद, बार, पे, पुन, मोड़े!",
          activityInstructionsHindi: "उंगलियां एक-एक करके दिखाते हुए संथाली संख्याएं बुलवाएं।",
          studentAction: "बच्चे उंगलियां गिनते हैं और संथाली में उच्चारण करते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 2: वस्तु प्रदर्शन (कंकड़ गिनती)",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱒: ᱫᱷᱤᱨᱤ ᱞᱮᱠᱷᱟ ᱩᱫᱩᱜ",
          durationMinutes: 10,
          teacherDialogueHindi: "देखो, मेरी मेज पर कितने कंकड़ हैं? एक, दो, तीन! संथाली में: मिद, बार, पे!",
          santaliOlChiki: "ᱧᱮᱞᱯᱮ, ᱤᱧᱟᱜ ᱢᱮᱡᱽ ᱨᱮ ᱛᱤᱱᱟᱹᱜ ᱫᱷᱤᱨᱤ ᱢᱮᱱᱟᱜ-ᱟ? ᱢᱤᱫ, ᱵᱟᱨ, ᱯᱮ!",
          santaliLatin: "Nyelpe, injag mej re tinag dhiri menag-a? Mit, Bar, Pe!",
          santaliDevanagari: "ञेलपे, इंद्याक मेज रे तिनाक धीरि मेनाक-आ? मिद, बार, पे!",
          activityInstructionsHindi: "बच्चों के सामने 3 कंकड़ रखें और 'ᱯᱮ' कार्ड साथ में रखें।",
          studentAction: "बच्चे वस्तुओं को गिनते हैं और कार्ड से मिलाते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 3: ओल चिकी अंक पहचान",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱓: ᱚᱞ ᱪᱤᱠᱤ ᱞᱮᱠᱷᱟ ᱪᱤᱱᱦᱟᱹᱣ",
          durationMinutes: 10,
          teacherDialogueHindi: "यह अंक देखो। यह ओल चिकी में '१' (मिद) है। इसे हवा में उंगली से लिखो।",
          santaliOlChiki: "ᱱᱚᱣᱟ ᱮᱞ ᱧᱮᱞᱯᱮ᱾ ᱱᱚᱣᱟ ᱫᱚ ᱚᱞ ᱪᱤᱠᱤ ᱛᱮ '᱑' (ᱢᱤᱫ) ᱠᱟᱱᱟ᱾ ᱦᱚᱭ ᱨᱮ ᱠᱟᱹᱴᱩᱵ ᱛᱮ ᱚᱞᱯᱮ᱾",
          santaliLatin: "Nowa el nyelpe. Nowa do Ol Chiki te '1' (Mit) kana. Hoy re katub te olpe.",
          santaliDevanagari: "नोवा एल ञेलपे। नोवा दो ओल चिकी ते '१' (मिद) काना। होय रे काटुब ते ओलपे।",
          activityInstructionsHindi: "बोर्ड पर ᱑, ᱒, ᱓, ᱔, ᱕ बड़े अक्षरों में लिखें।",
          studentAction: "बच्चे हवा में और अपनी स्लेट पर ओल चिकी अंक बनाते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 4: जोड़ी कार्य (संख्या मिलान खेल)",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱔: ᱡᱚᱲ ᱠᱟᱹᱢᱤ ᱟᱨ ᱞᱮᱠᱷᱟ ᱢᱮᱥᱟ",
          durationMinutes: 7,
          teacherDialogueHindi: "दो-दो बच्चे मिलकर 4 तीलियां चुनो और '४' (पुन) कार्ड के पास रखो।",
          santaliOlChiki: "ᱵᱟᱨ ᱵᱟᱨ ᱜᱤᱫᱽᱨᱟᱹ ᱢᱮᱥᱟ ᱠᱟᱛᱮ ᱯᱩᱱ (᱔) ᱜᱚᱴᱟᱝ ᱥᱟᱹᱲᱤ ᱵᱟᱪᱷᱟᱣᱯᱮ ᱟᱨ '᱔' ᱠᱟᱨᱰ ᱴᱷᱮᱱ ᱫᱚᱦᱚᱭᱯᱮ᱾",
          santaliLatin: "Bar bar gidra mesa kate pun (4) gotang sari bachawpe ar '4' card then dohoype.",
          santaliDevanagari: "बार बार गिद्रा मेसा काते पुन (४) गोटांग साड़ि बाछावपे आर '४' कार्ड ठेन दोहोयपे।",
          activityInstructionsHindi: "जोड़ियों में अभ्यास का अवलोकन करें।",
          studentAction: "बच्चे तीलियां गिनकर सही ओल चिकी संख्या कार्ड के साथ रखते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 5: सारांश एवं ताली",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱕: ᱥᱟᱨᱟᱝᱥᱚ ᱟᱨ ᱛᱟᱨᱤ",
          durationMinutes: 3,
          teacherDialogueHindi: "बहुत सुंदर! सभी बच्चे 5 बार ताली बजाएंगे: 1, 2, 3, 4, 5!",
          santaliOlChiki: "ᱟᱹᱰᱤ ᱱᱟᱯᱟᱭ! ᱥᱟᱱᱟᱢ ᱜᱤᱫᱽᱨᱟᱹ ᱢᱚᱬᱮ (᱕) ᱫᱷᱟᱣ ᱛᱟᱨᱤ ᱛᱷᱟᱭᱚᱭᱯᱮ: ᱢᱤᱫ, ᱵᱟᱨ, ᱯᱮ, ᱯᱩᱱ, ᱢᱚᱬᱮ!",
          santaliLatin: "Adi napay! Sanam gidra more (5) dhaw tari thayoepe: Mit, Bar, Pe, Pun, More!",
          santaliDevanagari: "अडी नापाय! सानाम गिद्रा मोड़े (५) धाव तारी थायोयपे: मिद, बार, पे, पुन, मोड़े!",
          activityInstructionsHindi: "तालियों के साथ गिनती दोहराते हुए कक्षा समाप्त करें।",
          studentAction: "बच्चे संथाली में बोलते हुए 5 बार ताली बजाते हैं।",
        ),
      ],
    ),
    LessonScript(
      id: "LS-LIT-02",
      titleHindi: "पाठ 3: ओल चिकी प्रथम वर्ण 'ᱚ' (ऑ) की ध्वनि एवं शब्द",
      titleSantali: "ᱯᱟᱴᱷ ᱓: ᱚᱞ ᱪᱤᱠᱤ ᱯᱩᱭᱞᱩ ᱟᱠᱷᱚᱨ 'ᱚ' ᱨᱮᱭᱟᱜ ᱥᱟᱰᱮ ᱟᱨ ᱥᱟᱵᱟᱫᱽ",
      competencyCode: "FL-G1-01",
      grade: FlnGrade.grade1,
      subject: FlnSubject.literacy,
      totalDurationMinutes: 35,
      learningOutcome: "बच्चे 'ᱚ' वर्ण की आकृति और ध्वनि पहचानेंगे तथा 'ᱚᱲᱟᱜ' (घर), 'ᱚᱞ' (लिखना) बोलेंगे।",
      materialsNeeded: [
        "'ᱚ' का फ्लैशकार्ड",
        "रेत की थाली (ट्रेसिंग के लिए)",
        "चित्र कार्ड: ओड़ाक (घर), ओल (लिखना)"
      ],
      phases: [
        LessonPhase(
          phaseNameHindi: "चरण 1: ध्वनि पहचान (ध्वनि सुनो)",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱑: ᱥᱟᱰᱮ ᱟᱸᱡᱚᱢ ᱟᱨ ᱪᱤᱱᱦᱟᱹᱣ",
          durationMinutes: 5,
          teacherDialogueHindi: "बच्चों, सुनो: 'ओड़ाक' (घर)! पहली आवाज़ क्या है? 'ऑ'!",
          santaliOlChiki: "ᱜᱤᱫᱽᱨᱟᱹᱠᱚ, ᱟᱸᱡᱚᱢᱯᱮ: 'ᱚᱲᱟᱜ'! ᱯᱩᱭᱞᱩ ᱥᱟᱰᱮ ᱫᱚ ᱪᱮᱫ? 'ᱚ'!",
          santaliLatin: "Gidrako, anjompe: 'Orag'! Puylu sade do chet? 'O'!",
          santaliDevanagari: "गिद्राको, आंजोमपे: 'ओड़ाक'! पुयलु साडे दो चेद? 'ओ'!",
          activityInstructionsHindi: "'ᱚ' ध्वनि पर जोर देते हुए 3 बार उच्चारण करें।",
          studentAction: "बच्चे 'ᱚ... ᱚ... ᱚ' का सस्वर उच्चारण करते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 2: वर्ण की बनावट",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱒: ᱟᱠᱷᱚᱨ ᱜᱚᱲᱦᱚᱱ ᱧᱮᱞ",
          durationMinutes: 10,
          teacherDialogueHindi: "यह है ओल चिकी का पहला अक्षर 'ᱚ'। यह गोल पृथ्वी जैसा है।",
          santaliOlChiki: "ᱱᱚᱣᱟ ᱫᱚ ᱚᱞ ᱪᱤᱠᱤ ᱨᱮᱭᱟᱜ ᱯᱩᱭᱞᱩ ᱟᱠᱷᱚᱨ 'ᱚ' ᱠᱟᱱᱟ᱾ ᱱᱚᱣᱟ ᱫᱚ ᱫᱷᱟᱹᱨᱛᱤ ᱞᱮᱠᱟ ᱜᱩᱞᱟᱹᱭ ᱜᱮᱭᱟ᱾",
          santaliLatin: "Nowa do Ol Chiki reyag puylu akhor 'O' kana. Nowa do dharti leka gulay geya.",
          santaliDevanagari: "नोवा दो ओल चिकी रेयाक पुयलु आखोर 'ओ' काना। नोवा दो धारती लेका गुलाय गेया।",
          activityInstructionsHindi: "बोर्ड पर बड़ा 'ᱚ' बनाएं और उंगली से ट्रेस करना सिखाएं।",
          studentAction: "बच्चे रेत में या हवा में 'ᱚ' की आकृति बनाते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 3: शब्द सम्बंध (शब्द बनाओ)",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱓: ᱥᱟᱵᱟᱫᱽ ᱡᱚᱲᱟᱣ",
          durationMinutes: 10,
          teacherDialogueHindi: "'ᱚ' से क्या होता है? 'ᱚ' से 'ᱚᱲᱟᱜ' (घर) और 'ᱚᱞ' (लिखना)।",
          santaliOlChiki: "'ᱚ' ᱛᱮ ᱪᱮᱫ ᱦᱩᱭᱩᱜ-ᱟ? 'ᱚ' ᱛᱮ 'ᱚᱲᱟᱜ' ᱟᱨ 'ᱚᱞ'᱾",
          santaliLatin: "'O' te chet huyug-a? 'O' te 'Orag' ar 'Ol'.",
          santaliDevanagari: "'ओ' ते चेद हुयुग-आ? 'ओ' ते 'ओड़ाक' आर 'ओल'।",
          activityInstructionsHindi: "घर का चित्र दिखाकर 'ᱚᱲᱟᱜ' कार्ड दिखाएं।",
          studentAction: "बच्चे 'ᱚᱲᱟᱜ' और 'ᱚᱞ' बोलते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 4: पहचान खेल",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱔: ᱟᱠᱷᱚᱨ ᱯᱟᱱᱛᱮ ᱮᱱᱮᱡ",
          durationMinutes: 7,
          teacherDialogueHindi: "कार्ड के ढेर में से 'ᱚ' खोजकर दिखाओ!",
          santaliOlChiki: "ᱠᱟᱨᱰ ᱜᱟᱫᱮᱞ ᱠᱷᱚᱱ 'ᱚ' ᱟᱠᱷᱚᱨ ᱯᱟᱱᱛᱮ ᱚᱰᱚᱠᱯᱮ!",
          santaliLatin: "Card gadel khon 'O' akhor pante odokpe!",
          santaliDevanagari: "कार्ड गादेल खोन 'ओ' आखोर पानते ओडोकपे!",
          activityInstructionsHindi: "मिश्रित कार्ड में से 'ᱚ' ढूँढने की गतिविधि करवाएं।",
          studentAction: "बच्चे कार्ड खोजकर उत्साह से दिखाते हैं।",
        ),
        LessonPhase(
          phaseNameHindi: "चरण 5: समापन",
          phaseNameSantali: "ᱫᱷᱟᱯ ᱕: ᱢᱩᱪᱟᱹᱫ ᱨᱚᱲ",
          durationMinutes: 3,
          teacherDialogueHindi: "बहुत बढ़िया! कल सभी बच्चे अपनी कॉपी में 5 बार 'ᱚ' लिखकर लाएंगे।",
          santaliOlChiki: "ᱟᱹᱰᱤ ᱵᱮᱥ! ᱜᱟᱯᱟ ᱥᱟᱱᱟᱢ ᱜᱤᱫᱽᱨᱟᱹ ᱟᱯᱱᱟᱨ ᱠᱷᱟᱛᱟ ᱨᱮ ᱢᱚᱬᱮ ᱫᱷᱟᱣ 'ᱚ' ᱚᱞ ᱠᱟᱛᱮ ᱟᱹᱜᱩᱭᱯᱮ᱾",
          santaliLatin: "Adi bes! Gapa sanam gidra apnar khata re more dhaw 'O' ol kate aguipe.",
          santaliDevanagari: "अडी बेस! गापा सानाम गिद्रा आपनार खाता रे मोड़े धाव 'ओ' ओल काते अगुइपे।",
          activityInstructionsHindi: "गृहकार्य का निर्देश दें।",
          studentAction: "बच्चे कार्य स्वीकार करते हैं।",
        ),
      ],
    ),
  ];

  // -------------------------------------------------------------
  // 3. CLASSROOM ACTIVITY INSTRUCTIONS SOUNDBOARD
  // -------------------------------------------------------------
  static const List<ClassroomInstruction> classroomInstructions = [
    ClassroomInstruction(
      id: "CI-01",
      category: "Classroom Management",
      hindi: "सभी बच्चे अपनी जगह पर बैठ जाओ।",
      santaliOlChiki: "ᱥᱟᱱᱟᱢ ᱜᱤᱫᱽᱨᱟᱹ ᱟᱯᱱᱟᱨ ᱴᱷᱟᱶᱨᱮ ᱫᱩᱲᱩᱵᱽᱯᱮ᱾",
      santaliLatin: "Sanam gidra apnar thaore durobpe.",
      santaliDevanagari: "सानाम गिद्रा आपनार ठावरे दुरुबपे।",
      pedagogicalTip: "कक्षा शुरू करते समय शांत वातावरण बनाने के लिए प्रयोग करें।",
    ),
    ClassroomInstruction(
      id: "CI-02",
      category: "Classroom Management",
      hindi: "अपनी-अपनी किताब और स्लेट निकालो।",
      santaliOlChiki: "ᱟᱯᱱᱟᱨ-ᱟᱯᱱᱟᱨ ᱯᱩᱛᱷᱤ ᱟᱨ ᱥᱞᱮᱴ ᱚᱰᱚᱠᱯᱮ᱾",
      santaliLatin: "Apnar-apnar puthi ar slet odokpe.",
      santaliDevanagari: "आपनार-आपनार पुथि आर स्लेट ओडोकपे।",
      pedagogicalTip: "शिक्षण सामग्री तैयार करवाते समय स्पष्ट निर्देश दें।",
    ),
    ClassroomInstruction(
      id: "CI-03",
      category: "Focus & Attention",
      hindi: "ब्लैकबोर्ड की तरफ ध्यान से देखो।",
      santaliOlChiki: "ᱠᱟᱹᱞᱤᱭᱟᱹ ᱵᱳᱨᱰ ᱥᱮᱫ ᱫᱷᱮᱭᱟᱱ ᱛᱮ ᱧᱮᱞᱯᱮ᱾",
      santaliLatin: "Kalia board sen dheyan te nyelpe.",
      santaliDevanagari: "कालिया बोर्ड सेद धेयान ते ञेलपे।",
      pedagogicalTip: "बोर्ड पर नया अक्षर या अंक लिखते समय बच्चों का ध्यान आकर्षित करें।",
    ),
    ClassroomInstruction(
      id: "CI-04",
      category: "Focus & Attention",
      hindi: "मेरी बात ध्यान से सुनो।",
      santaliOlChiki: "ᱤᱧᱟᱜ ᱠᱟᱛᱷᱟ ᱫᱷᱮᱭᱟᱱ ᱛᱮ ᱟᱸᱡᱚᱢᱯᱮ᱾",
      santaliLatin: "Injag katha dheyan te anjompe.",
      santaliDevanagari: "इंज्याक कथा धेयान ते आंजोमपे।",
      pedagogicalTip: "महत्वपूर्ण अवधारणा या कहानी सुनाने से पहले बोलें।",
    ),
    ClassroomInstruction(
      id: "CI-05",
      category: "Praise & Encouragement",
      hindi: "शाबाश! बहुत सुंदर किया।",
      santaliOlChiki: "ᱥᱟᱵᱟᱥ! ᱟᱹᱰᱤ ᱱᱟᱯᱟᱭ ᱯᱮ ᱠᱟᱹᱢᱤ ᱠᱮᱫᱟ᱾",
      santaliLatin: "Sabas! Adi napay pe kami keda.",
      santaliDevanagari: "साबास! अडी नापाय पे कामी केदा।",
      pedagogicalTip: "बच्चे के सही उत्तर या प्रयास पर तुरंत सकारात्मक प्रोत्साहन दें।",
    ),
    ClassroomInstruction(
      id: "CI-06",
      category: "Praise & Encouragement",
      hindi: "सब बच्चे इनके लिए ज़ोर से ताली बजाओ!",
      santaliOlChiki: "ᱥᱟᱱᱟᱢ ᱜᱤᱫᱽᱨᱟᱹ ᱱᱩᱭ ᱞᱟᱹᱜᱤᱫ ᱡᱩᱨ ᱛᱮ ᱛᱟᱨᱤ ᱛᱷᱟᱭᱚᱭᱯᱮ!",
      santaliLatin: "Sanam gidra nui lagid jur te tari thayoepe!",
      santaliDevanagari: "सानाम गिद्रा नुय लागिद जुर ते तारी थायोयपे!",
      pedagogicalTip: "सामूहिक प्रशंसा से बच्चों का आत्मविश्वास बढ़ता है।",
    ),
    ClassroomInstruction(
      id: "CI-07",
      category: "Movement & Action",
      hindi: "सभी बच्चे खड़े हो जाओ।",
      santaliOlChiki: "ᱥᱟᱱᱟᱢ ᱜᱤᱫᱽᱨᱟᱹ ᱛᱤᱸᱜᱩᱱᱯᱮ᱾",
      santaliLatin: "Sanam gidra tingunpe.",
      santaliDevanagari: "सानाम गिद्रा तिंगुनपे।",
      pedagogicalTip: "शारीरिक गतिविधि या बालगीत से पहले प्रयोग करें।",
    ),
    ClassroomInstruction(
      id: "CI-08",
      category: "Movement & Action",
      hindi: "हाथ ऊपर उठाओ और गोल घूमो।",
      santaliOlChiki: "ᱛᱤ ᱪᱚᱴ ᱛᱮ ᱛᱩᱞᱯᱮ ᱟᱨ ᱟᱹᱪᱩᱨᱚᱜᱽᱯᱮ᱾",
      santaliLatin: "Ti chot te tulpe ar achurogpe.",
      santaliDevanagari: "ती चोट ते तुलपे आर अचुरोकपे।",
      pedagogicalTip: "सुस्ती दूर करने के लिए एनर्जाइज़र गतिविधि में उपयोगी।",
    ),
    ClassroomInstruction(
      id: "CI-09",
      category: "Questioning & Interaction",
      hindi: "सब मिलकर एक साथ बोलो।",
      santaliOlChiki: "ᱥᱟᱱᱟᱢ ᱢᱮᱥᱟ ᱠᱟᱛᱮ ᱢᱤᱫ ᱥᱟᱶᱛᱮ ᱨᱚᱲᱯᱮ᱾",
      santaliLatin: "Sanam mesa kate mit sawte rorpe.",
      santaliDevanagari: "सानाम मेसा काते मिद सावते रोड़पे।",
      pedagogicalTip: "सस्वर पठन या कविता गायन के दौरान उपयोग करें।",
    ),
    ClassroomInstruction(
      id: "CI-10",
      category: "Questioning & Interaction",
      hindi: "जिसको उत्तर पता है, हाथ उठाओ।",
      santaliOlChiki: "ᱡᱟᱦᱟᱸᱭ ᱛᱮᱞᱟ ᱯᱮ ᱵᱟᱰᱟᱭᱟ, ᱛᱤ ᱛᱩᱞᱯᱮ᱾",
      santaliLatin: "Jahay tela pe badaya, ti tulpe.",
      santaliDevanagari: "जाहाय तेला पे बाड़ाया, ती तुलपे।",
      pedagogicalTip: "एक साथ चिल्लाने के बजाय अनुशासित भागीदारी को बढ़ावा देता है।",
    ),
    ClassroomInstruction(
      id: "CI-11",
      category: "Classroom Management",
      hindi: "पंक्ति (लाइन) में खड़े हो जाओ।",
      santaliOlChiki: "ᱫᱷᱟᱲᱤ ᱛᱮ ᱛᱤᱸᱜᱩᱱᱯᱮ᱾",
      santaliLatin: "Dhari te tingunpe.",
      santaliDevanagari: "धाड़ि ते तिंगुनपे।",
      pedagogicalTip: "प्रार्थना या मध्याह्न भोजन (MDM) के समय अनुशासन के लिए।",
    ),
    ClassroomInstruction(
      id: "CI-12",
      category: "Classroom Management",
      hindi: "हाथ धोकर खाना खाओ।",
      santaliOlChiki: "ᱛᱤ ᱟᱹᱨᱩᱵ ᱠᱟᱛᱮ ᱫᱟᱠᱟ ᱡᱚᱢᱯᱮ᱾",
      santaliLatin: "Ti arub kate daka jompe.",
      santaliDevanagari: "ती अरुब काते दाका जोमपे।",
      pedagogicalTip: "स्वच्छता और पोषण की अच्छी आदतें सिखाने हेतु।",
    ),
  ];

  // -------------------------------------------------------------
  // 4. FORMATIVE ASSESSMENT PROMPTS
  // -------------------------------------------------------------
  static const List<AssessmentPrompt> assessmentPrompts = [
    AssessmentPrompt(
      id: "AP-01",
      competencyCode: "FL-BV-01",
      grade: FlnGrade.balvatika,
      subject: FlnSubject.literacy,
      promptHindi: "यह किसका चित्र है? यह क्या खाता है?",
      promptSantaliOlChiki: "ᱱᱚᱣᱟ ᱫᱚ ᱚᱠᱚᱭᱟᱜ ᱪᱤᱛᱟᱹᱨ ᱠᱟᱱᱟ? ᱱᱩᱭ ᱫᱚ ᱪᱮᱫ-ᱮ ᱡᱚᱢᱟ?",
      promptSantaliLatin: "Nowa do okoyag chitar kana? Nui do chet-e joma?",
      promptSantaliDevanagari: "नोवा दो ओकोयाक चितार काना? नुय दो चेद-ए जोमा?",
      expectedResponseHindi: "यह गाय (गाई) है। यह घास (घांस) खाती है।",
      expectedResponseSantali: "ᱱᱩᱭ ᱫᱚ ᱜᱟᱹᱭ ᱠᱟᱱᱟᱭ᱾ ᱜᱷᱟᱸᱥ-ᱮ ᱡᱚᱢᱟ᱾ (Nui do gai kanay. Ghans-e joma.)",
      rubricBeginning: "केवल चित्र की ओर इशारा करता है या चुप रहता है।",
      rubricProgressing: "संथाली में केवल एक शब्द ('ᱜᱟᱹᱭ') बोलता है।",
      rubricProficient: "पूरे वाक्य में संथाली में बोलता है ('ᱜᱟᱹᱭ ᱠᱟᱱᱟᱭ, ᱜᱷᱟᱸᱥ ᱡᱚᱢᱟ')।",
    ),
    AssessmentPrompt(
      id: "AP-02",
      competencyCode: "FL-G1-01",
      grade: FlnGrade.grade1,
      subject: FlnSubject.literacy,
      promptHindi: "कार्ड देखकर बताओ, यह कौन सा ओल चिकी अक्षर है?",
      promptSantaliOlChiki: "ᱠᱟᱨᱰ ᱧᱮᱞᱛᱮ ᱞᱟᱹᱭᱢᱮ, ᱱᱚᱣᱟ ᱫᱚ ᱚᱠᱟ ᱚᱞ ᱪᱤᱠᱤ ᱟᱠᱷᱚᱨ ᱠᱟᱱᱟ?",
      promptSantaliLatin: "Card nyelte layme, nowa do oka Ol Chiki akhor kana?",
      promptSantaliDevanagari: "कार्ड ञेलते लयमे, नोवा दो ओका ओल चिकी आखोर काना?",
      expectedResponseHindi: "यह 'ᱚ' (ऑ) है और इससे 'ᱚᱲᱟᱜ' (घर) बनता है।",
      expectedResponseSantali: "ᱱᱚᱣᱟ ᱫᱚ 'ᱚ' ᱠᱟᱱᱟ, ᱚ ᱛᱮ ᱚᱲᱟᱜ᱾ (Nowa do 'O' kana, O te Orag.)",
      rubricBeginning: "अक्षर को नहीं पहचान पाता।",
      rubricProgressing: "अक्षर की ध्वनि 'ᱚ' बताता है लेकिन शब्द नहीं बता पाता।",
      rubricProficient: "अक्षर की सही ध्वनि और उससे शुरू होने वाला संथाली शब्द बताता है।",
    ),
    AssessmentPrompt(
      id: "AP-03",
      competencyCode: "FN-G1-01",
      grade: FlnGrade.grade1,
      subject: FlnSubject.numeracy,
      promptHindi: "मेज पर रखे इन पत्तों को संथाली में गिनकर बताओ कितने हैं?",
      promptSantaliOlChiki: "ᱢᱮᱡᱽ ᱨᱮ ᱫᱚᱦᱚ ᱟᱠᱟᱱ ᱥᱟᱠᱟᱢ ᱥᱟᱱᱛᱟᱲᱤ ᱛᱮ ᱞᱮᱠᱷᱟᱭᱢᱮ ᱛᱤᱱᱟᱹᱜ ᱢᱮᱱᱟᱜ-ᱟ?",
      promptSantaliLatin: "Mej re doho akan sakam Santali te lekhayme tinag menag-a?",
      promptSantaliDevanagari: "मेज रे दोहो आकान साकाम सांताड़ी ते लेखायमे तिनाक मेनाक-आ?",
      expectedResponseHindi: "एक, दो, तीन, चार - कुल चार (पुन) पत्ते हैं।",
      expectedResponseSantali: "ᱢᱤᱫ, ᱵᱟᱨ, ᱯᱮ, ᱯᱩᱱ - ᱡᱚᱛᱚ ᱛᱮ ᱯᱩᱱ (᱔) ᱜᱚᱴᱟᱝ ᱥᱟᱠᱟᱢ᱾ (Mit, bar, pe, pun - joto te pun gotang sakam.)",
      rubricBeginning: "गिनती में क्रम भूल जाता है या 2 से आगे नहीं गिन पाता।",
      rubricProgressing: "संथाली में 1 से 5 तक गिनता है परंतु अंतिम संख्या नहीं बता पाता।",
      rubricProficient: "वस्तुओं को एक-एक छूकर संथाली में सही गिनता है और कुल संख्या बताता है।",
    ),
    AssessmentPrompt(
      id: "AP-04",
      competencyCode: "FN-G2-01",
      grade: FlnGrade.grade2,
      subject: FlnSubject.numeracy,
      promptHindi: "तुम्हारे पास 3 बेर हैं और मित्र ने 2 और दिए, तो अब तुम्हारे पास कुल कितने बेर हैं?",
      promptSantaliOlChiki: "ᱟᱢ ᱴᱷᱮᱱ ᱯᱮ (᱓) ᱜᱚᱴᱟᱝ ᱡᱟᱹᱱᱩᱢ ᱛᱟᱦᱮᱸ ᱠᱟᱱᱟ ᱟᱨ ᱜᱟᱛᱮ ᱵᱟᱨ (᱒) ᱭᱟᱭ ᱮᱢᱟᱫ ᱢᱮᱭᱟ, ᱛᱚᱵᱮ ᱱᱤᱛ ᱛᱤᱱᱟᱹᱜ ᱦᱩᱭᱮᱱᱟ?",
      promptSantaliLatin: "Am then pe (3) gotang janum tahen kana ar gate bar (2) yay emad meya, tobe nit tinag huyena?",
      promptSantaliDevanagari: "आम ठेन पे (३) गोटांग जानुम ताहेन काना आर गाते बार (२) याय एमाद मेया, तोबे नित तिनाक हुयेना?",
      expectedResponseHindi: "तीन और दो मिलकर पाँच (मोड़े) बेर हुए।",
      expectedResponseSantali: "ᱯᱮ (᱓) ᱟᱨ ᱵᱟᱨ (᱒) ᱢᱮᱥᱟ ᱠᱟᱛᱮ ᱢᱚᱬᱮ (᱕) ᱜᱚᱴᱟᱝ ᱡᱟᱹᱱᱩᱢ ᱦᱩᱭᱮᱱᱟ᱾",
      rubricBeginning: "जोड़ने की प्रक्रिया नहीं समझ पाता।",
      rubricProgressing: "कंकड़ की सहायता से गिनकर 5 बताता है।",
      rubricProficient: "मौखिक रूप से तुरंत 'ᱢᱚᱬᱮ' (पाँच) बताता है और संथाली में समझाता है।",
    ),
  ];

  // -------------------------------------------------------------
  // 5. VISUAL FOUNDATIONAL FLASHCARDS
  // -------------------------------------------------------------
  static const List<VisualFlashcard> flashcards = [
    // Animals
    VisualFlashcard(
      id: "FC-01",
      category: "Animals",
      nipunLevel: FlnGrade.balvatika,
      hindi: "गाय",
      santaliOlChiki: "ᱜᱟᱹᱭ",
      santaliLatin: "Gai",
      santaliDevanagari: "गई",
      english: "Cow",
      icon: Icons.pets,
      cardColor: Color(0xFFE8F5E9),
      exampleSentenceHindi: "गाय घास खाती है।",
      exampleSentenceSantali: "ᱜᱟᱹᱭ ᱫᱚ ᱜᱷᱟᱸᱥ-ᱮ ᱡᱚᱢᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-02",
      category: "Animals",
      nipunLevel: FlnGrade.balvatika,
      hindi: "बकरी",
      santaliOlChiki: "ᱢᱮᱨᱚᱢ",
      santaliLatin: "Merom",
      santaliDevanagari: "मेरोम",
      english: "Goat",
      icon: Icons.cruelty_free,
      cardColor: Color(0xFFFFF3E0),
      exampleSentenceHindi: "बकरी का बच्चा खेल रहा है।",
      exampleSentenceSantali: "ᱢᱮᱨᱚᱢ ᱦᱚᱯᱚᱱ ᱮᱱᱮᱡ ᱠᱟᱱᱟᱭ᱾",
    ),
    VisualFlashcard(
      id: "FC-03",
      category: "Animals",
      nipunLevel: FlnGrade.balvatika,
      hindi: "कुत्ता",
      santaliOlChiki: "ᱥᱮᱛᱟ",
      santaliLatin: "Seta",
      santaliDevanagari: "सेता",
      english: "Dog",
      icon: Icons.pest_control_rodent,
      cardColor: Color(0xFFFBE9E7),
      exampleSentenceHindi: "कुत्ता घर की रखवाली करता है।",
      exampleSentenceSantali: "ᱥᱮᱛᱟ ᱚᱲᱟᱜ-ᱮ ᱨᱩᱠᱷᱤᱭᱟᱹᱭᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-04",
      category: "Animals",
      nipunLevel: FlnGrade.balvatika,
      hindi: "मुर्गी",
      santaliOlChiki: "ᱥᱤᱢ",
      santaliLatin: "Sim",
      santaliDevanagari: "सीम",
      english: "Hen / Chicken",
      icon: Icons.egg,
      cardColor: Color(0xFFFFFDE7),
      exampleSentenceHindi: "मुर्गी दाना चुग रही है।",
      exampleSentenceSantali: "ᱥᱤᱢ ᱫᱟᱱᱟᱭ ᱦᱟᱞᱟᱝ ᱮᱫᱟ᱾",
    ),

    // Numbers
    VisualFlashcard(
      id: "FC-05",
      category: "Numbers",
      nipunLevel: FlnGrade.grade1,
      hindi: "एक (1)",
      santaliOlChiki: "᱑ - ᱢᱤᱫ",
      santaliLatin: "1 - Mit",
      santaliDevanagari: "१ - मिद",
      english: "One (1)",
      icon: Icons.looks_one,
      cardColor: Color(0xFFE3F2FD),
      exampleSentenceHindi: "मेरे पास एक कलम है।",
      exampleSentenceSantali: "ᱤᱧ ᱴᱷᱮᱱ ᱢᱤᱫᱴᱟᱝ ᱠᱚᱞᱚᱢ ᱢᱮᱱᱟᱜ-ᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-06",
      category: "Numbers",
      nipunLevel: FlnGrade.grade1,
      hindi: "दो (2)",
      santaliOlChiki: "᱒ - ᱵᱟᱨ",
      santaliLatin: "2 - Bar",
      santaliDevanagari: "२ - बार",
      english: "Two (2)",
      icon: Icons.looks_two,
      cardColor: Color(0xFFE1F5FE),
      exampleSentenceHindi: "हमारी दो आँखें हैं।",
      exampleSentenceSantali: "ᱟᱵᱚᱣᱟᱜ ᱵᱟᱨᱭᱟ ᱢᱮᱫ ᱢᱮᱱᱟᱜ-ᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-07",
      category: "Numbers",
      nipunLevel: FlnGrade.grade1,
      hindi: "तीन (3)",
      santaliOlChiki: "᱓ - ᱯᱮ",
      santaliLatin: "3 - Pe",
      santaliDevanagari: "३ - पे",
      english: "Three (3)",
      icon: Icons.looks_3,
      cardColor: Color(0xFFE0F7FA),
      exampleSentenceHindi: "तिपहिया साइकिल में तीन पहिए होते हैं।",
      exampleSentenceSantali: "ᱯᱮ ᱪᱟᱠᱟ ᱜᱟᱹᱰᱤ ᱨᱮ ᱯᱮᱭᱟ ᱪᱟᱠᱟ ᱛᱟᱦᱮᱸᱱᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-08",
      category: "Numbers",
      nipunLevel: FlnGrade.grade1,
      hindi: "चार (4)",
      santaliOlChiki: "᱔ - ᱯᱩᱱ",
      santaliLatin: "4 - Pun",
      santaliDevanagari: "४ - पुन",
      english: "Four (4)",
      icon: Icons.looks_4,
      cardColor: Color(0xFFE0F2F1),
      exampleSentenceHindi: "मेज के चार पैर हैं।",
      exampleSentenceSantali: "ᱢᱮᱡᱽ ᱨᱮᱭᱟᱜ ᱯᱩᱱᱭᱟᱹ ᱡᱟᱝᱜᱟ ᱢᱮᱱᱟᱜ-ᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-09",
      category: "Numbers",
      nipunLevel: FlnGrade.grade1,
      hindi: "पाँच (5)",
      santaliOlChiki: "᱕ - ᱢᱚᱬᱮ",
      santaliLatin: "5 - More",
      santaliDevanagari: "५ - मोड़े",
      english: "Five (5)",
      icon: Icons.looks_5,
      cardColor: Color(0xFFEDE7F6),
      exampleSentenceHindi: "एक हाथ में पाँच उंगलियाँ हैं।",
      exampleSentenceSantali: "ᱢᱤᱫ ᱛᱤ ᱨᱮ ᱢᱚᱬᱮ ᱜᱚᱴᱟᱝ ᱠᱟᱹᱴᱩᱵ ᱢᱮᱱᱟᱜ-ᱟ᱾",
    ),

    // Body Parts
    VisualFlashcard(
      id: "FC-10",
      category: "Body Parts",
      nipunLevel: FlnGrade.balvatika,
      hindi: "आँख",
      santaliOlChiki: "ᱢᱮᱫ",
      santaliLatin: "Med",
      santaliDevanagari: "मेद",
      english: "Eye",
      icon: Icons.visibility,
      cardColor: Color(0xFFF3E5F5),
      exampleSentenceHindi: "हम आँखों से देखते हैं।",
      exampleSentenceSantali: "ᱟᱵᱚ ᱢᱮᱫ ᱛᱮᱵᱚ ᱧᱮᱞᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-11",
      category: "Body Parts",
      nipunLevel: FlnGrade.balvatika,
      hindi: "कान",
      santaliOlChiki: "ᱞᱩᱛᱩᱨ",
      santaliLatin: "Lutur",
      santaliDevanagari: "लुत्तुर",
      english: "Ear",
      icon: Icons.hearing,
      cardColor: Color(0xFFFCE4EC),
      exampleSentenceHindi: "हम कानों से सुनते हैं।",
      exampleSentenceSantali: "ᱟᱵᱚ ᱞᱩᱛᱩᱨ ᱛᱮᱵᱚ ᱟᱸᱡᱚᱢᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-12",
      category: "Body Parts",
      nipunLevel: FlnGrade.balvatika,
      hindi: "हाथ",
      santaliOlChiki: "ᱛᱤ",
      santaliLatin: "Ti",
      santaliDevanagari: "ती",
      english: "Hand",
      icon: Icons.front_hand,
      cardColor: Color(0xFFE8EAF6),
      exampleSentenceHindi: "हाथ से लिखो।",
      exampleSentenceSantali: "ᱛᱤ ᱛᱮ ᱚᱞᱢᱮ᱾",
    ),
    VisualFlashcard(
      id: "FC-13",
      category: "Body Parts",
      nipunLevel: FlnGrade.balvatika,
      hindi: "पैर",
      santaliOlChiki: "ᱡᱟᱝᱜᱟ",
      santaliLatin: "Janga",
      santaliDevanagari: "जांगा",
      english: "Leg / Foot",
      icon: Icons.directions_walk,
      cardColor: Color(0xFFE1BEE7),
      exampleSentenceHindi: "पैरों से चलो।",
      exampleSentenceSantali: "ᱡᱟᱝᱜᱟ ᱛᱮ ᱛᱟᱲᱟᱢᱢᱮ᱾",
    ),

    // Classroom & School
    VisualFlashcard(
      id: "FC-14",
      category: "Classroom",
      nipunLevel: FlnGrade.grade1,
      hindi: "किताब",
      santaliOlChiki: "ᱯᱩᱛᱷᱤ",
      santaliLatin: "Puthi",
      santaliDevanagari: "पुथि",
      english: "Book",
      icon: Icons.auto_stories,
      cardColor: Color(0xFFFFF8E1),
      exampleSentenceHindi: "यह मेरी किताब है।",
      exampleSentenceSantali: "ᱱᱚᱣᱟ ᱫᱚ ᱤᱧᱟᱜ ᱯᱩᱛᱷᱤ ᱠᱟᱱᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-15",
      category: "Classroom",
      nipunLevel: FlnGrade.grade1,
      hindi: "विद्यालय / स्कूल",
      santaliOlChiki: "ᱟᱥᱲᱟ",
      santaliLatin: "Asra (Iskul)",
      santaliDevanagari: "आसड़ा",
      english: "School",
      icon: Icons.school,
      cardColor: Color(0xFFDCEDC8),
      exampleSentenceHindi: "हम स्कूल जाते हैं।",
      exampleSentenceSantali: "ᱟᱵᱚ ᱟᱥᱲᱟ ᱵᱚ ᱥᱮᱱᱚᱜ-ᱟ᱾",
    ),
    VisualFlashcard(
      id: "FC-16",
      category: "Classroom",
      nipunLevel: FlnGrade.grade1,
      hindi: "पानी",
      santaliOlChiki: "ᱫᱟᱜ",
      santaliLatin: "Dak",
      santaliDevanagari: "दाक",
      english: "Water",
      icon: Icons.water_drop,
      cardColor: Color(0xFFE0F7FA),
      exampleSentenceHindi: "मुझे पानी पीना है।",
      exampleSentenceSantali: "ᱤᱧ ᱫᱟᱜ ᱧᱩᱭᱟᱹᱧ᱾",
    ),
    VisualFlashcard(
      id: "FC-17",
      category: "Classroom",
      nipunLevel: FlnGrade.grade1,
      hindi: "घर",
      santaliOlChiki: "ᱚᱲᱟᱜ",
      santaliLatin: "Orag",
      santaliDevanagari: "ओड़ाक",
      english: "Home / House",
      icon: Icons.home,
      cardColor: Color(0xFFFFCCBC),
      exampleSentenceHindi: "मेरा घर सुंदर है।",
      exampleSentenceSantali: "ᱤᱧᱟᱜ ᱚᱲᱟᱜ ᱟᱹᱰᱤ ᱪᱚᱨᱚᱠ-ᱟ᱾",
    ),
  ];
}
